### ISSUE TITLE
Smooth Scrollbar not working because componentWillReceiveProps is renamed

### ISSUE THREAD

**Issue by chtushar** [nghiepit/smooth-scrollbar-react#1]
I tried using this library on one of my projects, but it is not working. I tried recreating the problem in this instance
[https://codesandbox.io/s/goofy-sid-gnxuq](https://codesandbox.io/s/goofy-sid-gnxuq)

I think since componentWillReceiveProps is renamed that's why it is not working.
Please have a look at above link if there's any problem with my code.

Thanks in advance!

**Comment by nghiepdev** [comment]
@chtushar You just set the specific `height` or `max-height` the container element.
```diff
// styles.css
.App {
-min-height: 100vh;
+max-height: 100vh;
 width: 100%;
}
```

**Comment by chtushar** [comment]
It's working!!!! Thankyou so much. :)
