### ISSUE TITLE
How to implement scrollTo()

### ISSUE THREAD

**Issue by mhanifmuhsin** [nghiepit/smooth-scrollbar-react#10]
Can you help me , get scrollTo() in this library, because i have case for scroll to top function

**Comment by nghiepdev** [comment]
@mhanifmuhsin Example for scroll to top
https://codesandbox.io/s/smooth-scrollbar-react-forked-pzzn2?file=/src/App.tsx

**Comment by mhanifmuhsin** [comment]
thank you the code is working fine
