### ISSUE TITLE
Library block scroll in select option

### ISSUE THREAD

**Issue by mhanifmuhsin** [nghiepit/smooth-scrollbar-react#11]
I have a select option , but when I add this library the default scroll doesn't work, is it really like this, and is there a solution?

**Comment by nghiepdev** [comment]
@mhanifmuhsin Can you share your example code?

**Comment by mhanifmuhsin** [comment]
Yes, here is the sample code : [https://f91lz.csb.app/](sample code)

**Comment by nghiepdev** [comment]
@mhanifmuhsin 
I've just rewritten your example to works correct with `react-select`
https://codesandbox.io/s/sample-react-select-in-smooth-scroll-bar-forked-gv5uh?file=/src/MyComponent.jsx:1170-1461

**Comment by mhanifmuhsin** [comment]
Thank you, the code was successfully implemented and works well
