### ISSUE TITLE
smooth scrollbar version issue :)

### ISSUE THREAD

**Issue by ripe-avocado** [nghiepit/smooth-scrollbar-react#8]
Hello, my English is not good enough.....ㅜ
There is a tabindex issue because the smooth scrollbar version is low.
I understand it's been resolved in version 8.4.0 Please refer to the link below.
https://github.com/idiotWu/smooth-scrollbar/issues/152

I love this package. Thank you. :)

**Comment by nghiepdev** [comment]
@ripe-avocado I will rewrite the package soon and remove `smooth scrollbar` dependency.
You just install `smooth scrollbar` manually.

**Comment by nghiepdev** [comment]
@ripe-avocado Please try the new `2.0.0` version. Let me know your feedback.
