### ISSUE TITLE
Getting error on Next.js

### ISSUE THREAD

**Issue by pasindu-pr** [nghiepit/smooth-scrollbar-react#9]
Hey there,
Can't I use this on Next.js? I installed both smooth-scrollbar, smooth-scrollbar-react on my Next.js project. But I'm getting the following error.

import { __assign, __extends } from "tslib";
SyntaxError: Cannot use import statement outside a module

What should I do to fix this?

**Comment by nghieptiki** [comment]
You can share your codesandbox example?

**Comment by nghiepdev** [comment]
You can share your codesandbox example?

**Comment by pasindu-pr** [comment]
@nghiepit Check this please: 
https://codesandbox.io/s/next-with-react-smooth-scroll-bar-vew87?file=/pages/index.js

**Comment by nghiepdev** [comment]
@PasinduPrabhashitha I've just fixed
https://codesandbox.io/s/next-with-react-smooth-scroll-bar-forked-tmz82?file=/pages/index.js
